# Generated by Django 5.2.8 on 2025-11-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('flower', 'زهور'), ('fruit', 'فواكه'), ('vegetable', 'خضار'), ('herb', 'أعشاب')], default='flower', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='is_edible',
            field=models.BooleanField(default=False),
        ),
    ]
