# Generated by Django 5.2.8 on 2025-11-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plant_category_plant_is_edible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='plant',
            name='is_published',
        ),
        migrations.AddField(
            model_name='plant',
            name='care_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='plant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('flower', 'Flower'), ('herb', 'Herb'), ('succulent', 'Succulent'), ('tree', 'Tree'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
