# Generated by Django 5.2.8 on 2025-11-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_alter_plant_options_remove_plant_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={},
        ),
        migrations.RemoveField(
            model_name='plant',
            name='care_instructions',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='scientific_name',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='plant',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('flower', 'Flower'), ('herb', 'Herb'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='plants/default.jpg', upload_to='plants/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
