# Generated by Django 5.2.7 on 2025-11-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_remove_review_name_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(blank=True, choices=[('flower', 'Flower'), ('herb', 'Herb'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit')], max_length=20, null=True),
        ),
    ]
